Adamant-im/adamant-im

src/components/chat/AdmMessage.vue
src/components/chat/ChatEntryTemplate.vue
src/components/chat/CryptoTransfer.vue

- CryptoTransfer.vue: remove unused div `message-tick`
- Chat: display icon confirmation for DOGE & ETH
- Chats: display icon confirmation only for transactions

fix(chat): fix confirmation icon

---

src/components/transactions/Erc20Transaction.vue
src/components/transactions/EthTransaction.vue
src/store/modules/eth-base/eth-base-actions.js
src/store/modules/eth/actions.js

`gasPrice` could be missing in some cases for the ETH transactions.

Fixed broken ETH/ERC20 fee calculation

---

src/filters/numberFormat.js
src/main.js
src/views/Home.vue

When displaying balances on home tab, we do not need more than 4 significant digits shown.

Remove not needed numbers

---

src/store/modules/eth-base/eth-base-mutations.js

`recipientId` may be missing, e.g., when the mutation is called to change the transaction status only.

Fixed `direction` for the ETH/ERC20 transfers

---

src/components/WalletCardListActions.vue
src/components/transactions/TransactionTemplate.vue
src/views/Votes.vue

While we are opening windows that we trust, we can't be sure that they won't be hacked some day. So we need to defend our window from access using window.opener.

We should add noopener option to ALL windows opened with window open

---

src/mixins/transaction.js
src/store/modules/btc-base/btc-base-actions.js
src/store/modules/eth-base/eth-base-actions.js

- 5 attempts
- 5 sec interval (old transactions)
- 60 sec interval (new transactions)

ETHLike and BTCLike: timeout, interval, attempts

---

.gitignore
README.md
electron-builder.yml
electron-vite.config.ts
package.json
src/electron/main.js

fix(electron): fix white screen after production build
* feat(src/electron/main.js): use custom `app://` scheme instead of `file://`
* fix(electron-builder.yml): exclude unused files before packaging to reduce the app size
* chore(electron-vite.config.ts): set `build.outDir` to `dist-electron` when building Vue app for Electron
* chore(electron-builder.yml): packaged apps will be placed in `./release-electron`

Fix electron white screen after production build

---

vite.config.ts

https://trello.com/c/KljLS5TJ/356-the-app-is-trying-to-load-the-old-js-file-due-to-the-sw-cache

fix(VitePWA): main.js is not cached by SW due to `maximumFileSizeToCacheInBytes`

---

src/components/ChatPreview.vue

https://trello.com/c/Lw45qdDZ/355-bug-make-loading-chat-animation-centered
Not sure this is the same as on https://msg.adamant.im/chats because I don't have enough chats to check but I basically just centered the element so there should be no room for error

center loading element

---

src/assets/styles/components/_chat.scss
src/components/AChat/AChat.vue

https://trello.com/c/7jZEG9rt/228-bug-multiple-strings-hide-last-messages

fix(ChatForm): don't overflow the chat when typing a multiline message

---

src/assets/styles/components/_chat.scss

https://trello.com/c/PccXlMC7/390-bug-message-entry-field-missing

fix(Chat): Android navigation menu overflows chat form

---

package-lock.json
package.json
src/lib/transactionsFetching.js

https://trello.com/c/tGvN9PhE/417-bug-after-adm-sending-the-app-sends-infinite-requests

fix(`/transactions/ADM/:id`, updateStatus): app sending infinite requests

---

src/components/Chat/Chat.vue

https://trello.com/c/Wsl1Cad2/410-bug-retrieving-quoted-quoted-message-loads-all-the-message-history

fix(Chat): reply message click loads all chat history

---

src/components/ChatPreview.vue

Resolves https://trello.com/c/yRtWY0uF/433-ui-reduce-name-field-size-in-the-chat-list-screen

fix(chat): added ellipsis for long chat names

---

src/assets/styles/generic/_vuetify.scss
src/components/Chat/Chat.vue

Before
After
https://trello.com/c/czApsWrP/216-feat-show-new-messages-count-in-chat-view-fab

Feat/ scroll to bottom fab new messages counter

---

src/components/AChat/AChatForm.vue
src/components/Chat/Chat.vue

[(after)Preserve message text in the input field.webm](https://github.com/Adamant-im/adamant-im/assets/122323015/d81bacf2-c49c-4ee9-8e2b-9ed027600b90)

feat: preserve message text in the input field

---

src/mixins/transaction.js
src/store/modules/chat/index.js

Show inconsistent status for duplicate crypto transactions instead of hiding duplicates.
Here is another [task](https://trello.com/c/T0lBJNp9/464-refactor-transactionjs-mixin) for refactoring the transaction mixin. Now it looks complicated. This PR can be considered as an workaround.

feat(Transaction): show inconsistent status if it's a duplicate

---

src/mixins/transaction.js
src/store/modules/chat/index.js

Reverts Adamant-im/adamant-im#561

Revert "feat(Transaction): show inconsistent status if it's a duplicate"

---

src/assets/styles/app.scss
src/assets/styles/components/_arrow-return.scss
src/components/AChat/AChatReplyPreview.vue
src/components/AChat/QuotedMessage.vue
src/components/ChatPreview.vue
src/lib/markdown.js

feat: multi line sumbol

---

package.json
src/components/Chat/Chat.vue
src/components/Chat/ChatEmojis.vue
src/components/Chat/ChatMenu.vue
src/components/EmojiPicker.vue

Fix for hidden emojis selector on Chrome (iOS

fix: emojis are not visible on iOS Chrome

---

package-lock.json
package.json
src/components/AChat/AChatForm.vue
src/lodash.uniq.d.ts
src/store/modules/bot-commands/bot-commands-actions.ts
src/store/modules/bot-commands/bot-commands-getters.ts
src/store/modules/bot-commands/bot-commands-mutations.ts
src/store/modules/bot-commands/bot-commands-state.ts
src/store/modules/bot-commands/index.ts
src/store/modules/bot-commands/types.ts
src/store/modules/bot-commands/utils/extractCommandsFromMessages.ts
src/store/modules/bot-commands/utils/uniqCommand.ts
src/store/modules/chat/index.js
src/store/modules/draft-message/index.ts

https://trello.com/c/oMvsGyEs/527-commands-shouldnt-be-in-asc-order
- The last command entered must be the first in the list.
- Load command history on start
[Screencast from 26.03.2024 15:44:27.webm](https://github.com/Adamant-im/adamant-im/assets/160286261/48a1c6e3-948c-499d-aa4e-5d5b85569616)

fix: commands shouldn't be in ASC order

---

src/components/AChat/AChatForm.vue

Trello: [task]( https://trello.com/c/oMvsGyEs/527-commands-shouldnt-be-in-asc-order)
[fix: scroll between commands .webm](https://github.com/Adamant-im/adamant-im/assets/160286261/9ad38edf-34b4-4b9a-8b13-0a7c8c5e23fc)

fix: scroll between commands only when the input field focused

---

src/components/AChat/AChatForm.vue

https://trello.com/c/oMvsGyEs/527-commands-shouldnt-be-in-asc-order
[fix: multiline text.webm](https://github.com/Adamant-im/adamant-im/assets/160286261/af68228a-5c0e-4a62-ba6c-1f9ee6857b8e)

fix: unable to move up/down cursor in a multiline message

---

.github/workflows/electron-mac.yml
electron-builder.yml

- fix: disable `electron-builder` notarization
- fix: try notarization by hook after pack and before sign

fix: Electron for Mac build failed

---

src/components/WalletCard.vue

A balance that contains many symbols should only be shown in full on wide screens (Picture 1)
On phones it’s worth showing a shortened version (Picture 2)

feat: smart balance on account tab (copied from iOS)

---

src/store/modules/wallets/wallets-actions.ts

- fix: remove vuex-dispatch of none-existent method `checkWalletsOrderBeforeInit`

fix: [vuex] Unknown local action type: checkWalletsOrderBeforeInit

---

src/components/QrcodeScannerDialog.vue
src/lib/zxing/index.ts
src/locales/de.json
src/locales/en.json
src/locales/ru.json
src/locales/zh.json

- feat: no camera access or video stream info in modal window

feat: No camera access or video stream info in modal window

---

src/lib/markdown.js

- fix: broken links are shown as undefined

Fix: Broken links — are shown as undefined

---

commitlint.config.js
commitlint.config.ts
package-lock.json
package.json

- Added `type: "module"` to package.json (see https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated)
- Upgraded `vitest`
- Switched commitlint configuration to ESM

Switch from CJS to ESM build (modern browsers)

---

src/components/AppToolbarCentered.vue
src/components/Chat/ChatToolbar.vue
src/components/common/BackButton/BackButton.vue

Every single page mentioned in this task - https://trello.com/c/ZEobk2Jg/748-ui-use-same-style-back-arrows-on-different-screens uses the same component with a 'back' button, so it was enough to change this button there.

chore: use the same style for back button as it was in chat room

---

src/components/AChat/AChatReplyPreview.vue
src/components/AChat/QuotedMessage.vue
src/components/ChatPreview.vue
src/lib/markdown.ts
src/lib/notifications.js

Please check using this text:
```
Simple # text
```

fix: formatting for markdown headings in chat list and notifications

---

scripts/electron/sandboxFix.mjs

getting path by js is not working in github. Rollback to bash

fix: electron linux build get path by bash

---

index.html

Mark fix as potential as I didn't manage to recreate the bug on localhost. So I can't check whether it really fixes the problem but it looks like it might help.

fix: potential fix favicon error in console on chat page

---

src/App.vue

Fix black color overflow when light theme is turned on

fix: fix black overflow when light theme is turned on
