Adamant-im/adamant-im

src/components/Chat.vue

Allow to send messages in chat by Cmd + Enter

Fix #30, send message with Cmd + Enter

---

src/lib/notifications.js

a component can now import the notifications library to send
browser notifications to the user.
import notification from '../lib/notifications'
notification.notify('Adamant.im alert', {
text: 'You have been logged in!',
handler: () => {
console.log('user clicked notification!')
}
})

browser notifications library

---

src/components/Login.vue
src/components/QRScan.vue
src/i18n/en.js
src/main.js

- show tooltip on button
- display invalid passphrase when qr scan fails
- redirect back to homepage

fixups on qr code scan

---

package-lock.json
src/lib/constants.js
src/store/index.js

Fixed app crash, if pass phrase was not encoded

Fix bug with encoded pass phrase

---

src/components/Chat.vue
src/components/Chats.vue
src/components/Login.vue
src/components/chat/AdmMessage.vue
src/components/chat/ChatEntry.vue
src/components/chat/ChatEntryTemplate.vue
src/store/index.js

According to spec were added generated welcome messages

Added welcome messages

---

src/components/Transfer.vue

Reverts Adamant-im/adamant-im#105

Revert "Fix bug with recipient name"

---

src/components/Chats.vue
src/i18n/en.js
src/i18n/ru.js

Lang strings and console warnings

Small updates

---

deploy.sh

Make index.html default router for surge deployments
Allow all resources on CORS

Surge.sh deployment fixes

---

src/App.vue
src/components/userpassword/LoginWithUserPassword.vue
src/components/userpassword/SetUserPassword.vue
src/lib/adamant-api.js
src/lib/indexedDb.js
src/lib/lsStore.js
src/store/index.js
src/store/modules/adm/adm-actions.js
src/views/Chats.vue

Fix problem when sometimes chats were marked as unread after login with password.

Adamantpwa 103

---

src/store/index.js

ADM will check it on server side anyway

Don't check ADM balance before storing crypto address

---

src/lib/store-crypto-address.js
src/store/index.js
src/store/modules/doge/doge-actions.js
src/store/modules/eth/actions.js

Try to store crypto addresses periodically to make sure they make it to the KVS as soon as user has enough ADMs.

Store crypto address properly

---

src/i18n/en.json
src/i18n/ru.json
src/views/Transactions.vue

style `No transactions yet` headline

---

src/store/modules/eth-base/eth-base-actions.js

Sometimes api seems to returns empty objects

Check for transaction object

---

src/store/modules/doge/doge-actions.js
src/store/modules/eth-base/eth-base-actions.js

Re-request crypto transfer details if nothing has been returned from server

---

src/components/chat/CryptoTransfer.vue
src/store/modules/eth-base/eth-base-actions.js

What was that `checkBlockCount` for?

Fixed ETH/ERC20 statuses updating

---

src/components/LanguageSwitcher.vue
src/views/Login.vue

Little animation never hurt anyone

Add animation to language selector and icons

---

src/components/AChat/AChatMessage.vue
src/components/Chat/Chat.vue
src/components/Chat/ChatToolbar.vue

* Show partners avatar in toolbar
* Hide avatars inside message on mobile phones

Avatars in chat window

---

package.json
src/components/PassphraseGenerator.vue
src/lib/adamant.js
src/lib/eth-utils.js
vue.config.js
yarn.lock

Bip39 was update to typescript version, also default calls now async. So i replaced calls to sync methods, added treeshaking in vue-config to shrink it to just 33kb out of 208kb.

Update bip39 to version 3.0.1

---

public/index.html

Because js size is pretty big, loading on slow 3g can take time, i suggest setting simple preloader animation to be displayed instead of white screen before initialisation occurs

Add preloader

---

src/store/modules/eth-base/eth-base-actions.js

ADAMANTPWA-355
- Get block number from eth_getTransactionByHash, then get timestamp by eth_getBlockByNumber.

Retrieve ETH/ERC20 transaction timestamp

---

src/components/ChatPreview.vue
src/store/modules/chat/index.js

- Display nothing in ChatBrief if chat has no messages
- Display new chats at the top

fix(ChatBrief): new chat without messages

---

src/router/index.js
src/views/Home.vue
src/views/Nodes.vue
src/views/Options.vue

- Fix Container padding in Account View, Nodes View
- Remove VListTile padding in Options View

Style changes

---

src/store/modules/btc-base/btc-base-actions.js
src/store/modules/eth-base/eth-base-actions.js

Reverts Adamant-im/adamant-im#327

Revert "Fix/transactions statuses and multiple requests"

---

src/lib/adamant-api-client.js

Bug: Good nodes in Sync status.

Revert: feat(ApiClient): single winner, other nodes should be sync

---

package-lock.json
package.json

Must fix `sodium-native` rebuild fatal error

Downgrade `electron-builder` to the latest stable version

---

package-lock.json
package.json
vite.config.ts

fix(`hdkey` package): add browser polyfill for Node.js `assert` module

---

package-lock.json
package.json
src/components/QrcodeCapture.vue

- Upgraded `@zxing/library`: 0.19.2 -> 0.20.0
- Fixed authorisation by QR code (https://trello.com/c/T2OJT73d/329-authorization-by-file-with-a-qr-code-does-not-work)

Authorization by file with a QR code does not work

---

package-lock.json
package.json
src/components/ChatStartDialog.vue
src/components/QrcodeCapture.vue

Replace `@zxing/library` with `@zxing/browser`

"Start a new chat: Read QR from image" doesn't work

---

src/components/ChatStartDialog.vue

https://trello.com/c/8QGyG9co/334-ui-wrong-pointer

fix(ChatStartDigalog): show cursor pointer when hovering "Read QR from image"

---

src/components/Chat/ChatToolbar.vue

https://trello.com/c/bXo991Y9/337-bug-returning-back-from-chat-doesnt-restore-position

fix(chats): when navigating back from `/chat/:id` to `/chats` the scroll position is lost

---

src/views/Transactions.vue

https://trello.com/c/sO5bELsb/340-bug-adm-tx-history-lacks-txs

Bug: ADM tx history lacks txs

---

src/assets/styles/app.scss
src/assets/styles/generic/_list.scss

https://trello.com/c/q91ZV3ZZ/349-bug-list-style

add _list.scss file

---

src/components/DelegatesTable/DelegateDetailsExpander.vue
src/components/DelegatesTable/DelegatesTable.vue
src/components/DelegatesTable/DelegatesTableHead.vue
src/components/DelegatesTable/DelegatesTableItem.vue

https://trello.com/c/cGrS5NDE/342-ui-delegate-details

remove borders on dark theme

---

src/views/Transactions.vue

https://trello.com/c/0QIWLMyP/353-bug-no-spinner-when-loading-tx-list

Fix no spinner bug

---

src/components/ChatPreview.vue
src/lib/notifications.js

[… notification formatting](https://trello.com/c/djD3bedK)

add function calling for chat preview formatting and if statement for notification formatting

---

src/components/QrcodeRenderer.vue

add spinner for qrcoderenderer

---

src/App.vue
src/store/index.js

Fixes https://trello.com/c/VKkOWNmR/382-bug-erc20-coins-dont-work-after-refresh

Bug: ERC20 coins don't work after refresh

---

package.json
scripts/wallets.mjs

https://trello.com/c/Ksxc3W1s/396-javascript-error-occurred-when-running-electron-app-on-mac

fix(electron, package.json): can't launch Electron app due to ES/CJS error

---

package-lock.json
src/components/NodesTable/NodesTableItem.vue

fix(Nodes): use `$adm-colors` instead of Vuetify colors

---

.github/workflows/electron-linux.yml
.github/workflows/electron-mac.yml
.github/workflows/electron-windows.yml
.github/workflows/preview.yml
.gitignore
openapitools.json
package-lock.json
package.json
scripts/adamant-schema/generate.mjs
src/lib/schema/config.json
src/lib/schema/schema.json

https://trello.com/c/mZ0ZsNwj/412-generate-ts-types-from-adamant-schema-repo

chore(TypeScript): generate types from `adamant-schema`

---

src/views/Options.vue

https://trello.com/c/K6Cjqo96/420-bug-stay-logged-in-doesnt-work

fix(Settings): stay logged in option doesn't work

---

src/components/ExportKeysForm.vue
src/components/LoginForm.vue
src/components/PasswordSetDialog.vue

https://trello.com/c/Om8o4eFy/389-feat-add-an-option-to-see-a-passphrase

feat: show/hide passphrase in text inputs

---

src/lib/constants/cryptos/data.json

https://trello.com/c/XC3peJqN/435-feat-add-verse-token-verse-token-icon-pack
adamant-wallets: https://github.com/Adamant-im/adamant-wallets/pull/42

feat(`adamant-wallets`): add Verse token

---

src/App.vue
src/assets/styles/components/_chat.scss
src/lib/markdown.js

feat: beautiful code markdown

---

src/lib/__tests__/eth-utils.spec.js
src/lib/eth-utils.js
src/store/modules/erc20/erc20-actions.js
src/store/modules/eth/actions.js

- Added `increaseFee()` helper

fix(ETH/ERC20): round `gasLimit` before converting to BigInt

---

src/components/Chat/ChatToolbar.vue
src/store/modules/chat/index.js

feat:show unread count over the back button

---

src/views/Home.vue

Fix/ changed the style for the vertical arrow button

---

src/components/DelegatesTable/DelegatesTable.vue
src/views/Votes.vue

fix: search delegates by page

---

src/lib/vibrate.js
src/router/index.js
src/views/Vibro.vue

feat: page with sound vibrations

---

package-lock.json
package.json
src/lib/constants/cryptos/data.json

Hot fix. Target `master` is on purpose.

fix(adamant-wallets): fix GT decimals

---

package-lock.json
package.json

Release v.4.6.0

---

src/components/AChat/AChatForm.vue

[Screen recording 2024-05-01 20.06.31.webm](https://github.com/Adamant-im/adamant-im/assets/122323015/638ebfec-b872-42bf-bfb7-6c599df35cc2)

fix: the bottom border of the input field is blue

---

src/router/index.js
src/views/Nodes.vue
src/views/Wallets.vue

[Screen recording 2024-05-02 00.52.28.webm](https://github.com/Adamant-im/adamant-im/assets/122323015/d3cab01e-2b42-4168-a86b-58a181469f9b)

fix: scroll in wallets and nodes page

---

src/components/nodes/components/NodeUrl.vue

- fix: incorrect url formatting for localhost on coin nodes
- chore: simplify condition for displaying domain

fix: Incorrect URL formatting for localhost on Coin Nodes tab

---

android/app/build.gradle
android/variables.gradle
package-lock.json
package.json

Set API Level 22+ (Android 5.1 or later)

Release 4.7.2

---

public/.well-known/apple-app-site-association
public/.well-known/assetlinks.json

- feat: add `.well-known` dir in `public` dir

feat: Create .well-known dir after build

---

src/assets/styles/settings/_colors.scss
src/components/DelegatesTable/DelegatesTable.vue
src/components/nodes/components/NodesTableContainer.vue
src/views/Wallets.vue

- chore: change nodes, wallets and votes tables backgrounds
- chore: remove imports with custom scss mixins

chore: UI: Restyle tables

---

src/lib/adamant-api/index.js

This scenario may occur in-between the `GET /states/get` and `POST /state/store` requests, if the first request is pending while the user logs into another account. A check has been added to interrupt the second request.
https://trello.com/c/0kgxXGmj/639-wrong-wallet-address-stored-in-kvs-while-logging-into-another-account

fix(KVS): wrong wallet address stored in KVS while logging into another account

---

src/components/transactions/BtcTransaction.vue
src/components/transactions/Erc20Transaction.vue
src/components/transactions/EthTransaction.vue
src/components/transactions/KlyTransaction.vue
src/components/transactions/TransactionTemplate.vue
src/components/transactions/hooks/useTransactionStatus.ts
src/hooks/queries/transaction/useTransactionStatusQuery.ts

https://trello.com/c/75xU6VY2/600-bug-changing-tx-status-after-sending-usdt

fix(transfer): transaction status changed from Confirmed to Pending when sending USDT

---

src/lib/nodes/abstract.node.ts

[Screencast from 20.02.2025 00:19:59.webm](https://github.com/user-attachments/assets/a4528085-3eaa-4bf9-af35-90f09e25866e)

fix: send a healthcheck request only if such request is not currently being executed

---

src/store/index.js
src/store/utils/coinUpdatesGuard.ts

wallets/getVisibility getter return undefined, need to recheck visibility after all wallets init

fix: change shouldUpdate callback for wallet status

---

src/assets/styles/generic/_vuetify.scss

fix: missing some lines on the in-chat transfer screen (on light theme)

---

src/config/development.json
src/config/production.json
src/config/tor.json

Changelog: https://github.com/Adamant-im/adamant-wallets/pull/110
`npm run wallets:generate`

chore: regenerate `adamant-wallets`

---

src/components/LoginPasswordForm.vue

https://trello.com/c/oHrMYNZo/677-ui-add-show-hide-password-icon-when-login-by-password-enabled

feat: add show/hide function when login with password is enabled

---

.github/workflows/github-pages.yml
README.md

docs(README.md): add instructions for self-hosted app on GH Pages

---

src/components/WarningOnAddressesDialog.vue
src/components/WarningOnPartnerAddressDialog.vue
src/lib/store-crypto-address.js

These dialogs were broken (not shown).
Now you'll see them when (1) Enter test account (2) Send crypto to Alex Hathaway.
I know code is awful but (1) I didn't do worse with this pr (2) You can refactor in another pr.

Fix Warning on address dialog(s)

---

src/components/LoginForm.vue
src/components/LoginPasswordForm.vue
src/hooks/useSaveCursor.ts

https://trello.com/c/oHrMYNZo/677-ui-add-show-hide-password-icon-when-login-by-password-enabled

fix: save cursor position when changing visibility

---

src/assets/styles/generic/_list.scss

fix: markdown list padding

---

src/components/EmojiPicker.vue

Potential fix bug with not working emoji button in chat on github pages deployed version.

fix: fix bug with emoji section on github pages

---

src/components/PassphraseGenerator.vue

Update for
https://github.com/Adamant-im/adamant-im/pull/771
UI: Update Login screen
https://trello.com/c/BSC1qMxn

Chore: Update passphrase's asterisk sign and margin for icons

---

src/views/ExportKeysForm.vue

Closes: https://trello.com/c/3nfbVGJB
* Add margin-top to ExportKeysForm

chore: add margin top to exportkeysform

---

src/views/ExportKeysForm.vue

Closes: https://trello.com/c/3nfbVGJB
* Add more margin-top to ExportKeysForm
* Add margin-top to disclaimer in the form

chore: add margin top to exportkeysform (2)
